version: "3"
services:
  analysis:
    image: joelnitta/pleurosoriopsis
    ports:
      - "8787:8787"
    volumes:
      - ".:/home/rstudio/pleurosoriopsis"
    environment:
      PASSWORD: "ilover"
      ROOT: "true"