version: "3"
services:
  analysis:
    image: joelnitta/pleurosoriopsis
    ports:
      - "8787:8787"
    volumes:
      - ".:/home/rstudio/pleurosoriopsis"
    environment:
      DISABLE_AUTH: "true"
    working_dir: /home/rstudio/pleurosoriopsis