version: "3"
services:
  analysis:
    image: joelnitta/eupoly2_capture
    ports:
      - "8787:8787"
    volumes:
      - ".:/home/rstudio/Pleurosoriopsis"
    environment:
      PASSWORD: "ilover"
      ROOT: "true"
  rmd:
    image: joelnitta/rmd
    ports:
      - "7070:8787"
    volumes:
      - ".:/home/rstudio/Pleurosoriopsis"
    environment:
      PASSWORD: "ilover"
      ROOT: "true"
